esphome:
  name: backroof
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: 'iot'
  domain: ".lan.0x20.be"
  password: !secret wifipassword
  fast_connect: false

api:

logger:
  level: debug

debug:
  update_interval: 5s

ota:

mqtt:
  broker: mqtt.lan.0x20.be
  topic_prefix: "hsg/backroof"
  on_message:
    - topic: "hsg/backroof/direction"
      payload: "0"
      then:
        if:
          condition:
            switch.is_on: relay_dir
          then:
            - switch.turn_on: relay_en
            - switch.turn_off: relay_dir
    - topic: "hsg/backroof/direction"
      payload: "1"
      then:
        if:
          condition:
            switch.is_off: relay_dir
          then:
            - switch.turn_on: relay_en
            - switch.turn_on: relay_dir
    - topic: "hsg/backroof/power"
      payload: "1"
      then:
        if:
          condition:
            switch.is_off: relay_en
          then:
            - switch.turn_on: relay_en
    - topic: "hsg/backroof/power"
      payload: "0"
      then:
        if:
          condition:
            switch.is_on: relay_en
          then:
            - switch.turn_off: relay_en

binary_sensor:
  - platform: gpio
    name: "switch down"
    pin:
      number: D5
      mode: INPUT_PULLUP
      inverted: true
    filters:
      - delayed_on_off: 100ms
    on_press:
      then:
        - switch.turn_off: relay_dir
        - switch.turn_on: relay_en
    on_release:
      then:
        - switch.turn_off: relay_en
  - platform: gpio
    name: "switch up"
    pin:
      number: D2
      mode: INPUT_PULLUP
      inverted: true
    filters:
      - delayed_on_off: 100ms
    on_press:
      then:
        - switch.turn_on: relay_dir
        - switch.turn_on: relay_en
    on_release:
      then:
        - switch.turn_off: relay_en

switch:
  - platform: gpio
    name: "roof enable relay"
    id: relay_en
    pin: D3
    inverted: false
    restore_mode: RESTORE_DEFAULT_ON
#    on_turn_on:
#      - mqtt.publish:
#          topic: "hsg/backroof/power"
#          payload: "1"
#          retain: true
#    on_turn_off:
#      - mqtt.publish:
#          topic: "hsg/backroof/power"
#          payload: "0"
#          retain: true
  - platform: gpio
    name: "roof direction relay"
    id: relay_dir
    pin: D4
    inverted: true
    restore_mode: RESTORE_DEFAULT_OFF
#    on_turn_on:
#      - mqtt.publish:
#          topic: "hsg/backroof/direction"
#          payload: "1"
#          retain: true
#    on_turn_off:
#      - mqtt.publish:
#          topic: "hsg/backroof/direction"
#          payload: "0"
#          retain: true

status_led:
  pin:
    number: D1
    inverted: yes
