esphome:
  name: switch-socket
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "iot"
  domain: ".lan.0x20.be"
  password: !secret wifipassword
  fast_connect: false

api:

logger:

ota:

mqtt:
  broker: mqtt.lan.0x20.be
  topic_prefix: "hsg/switch-socket"
  on_message:
    topic: "hsg/switch-socket/toggle"
    then:
      - switch.toggle: relay

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff Basic Button"
    on_press:
      - switch.toggle: relay
      - mqtt.publish:
          topic: "hsg/switch-socket/toggle"
          payload: "button pressed"
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff Basic Button"
    on_press:
      - switch.toggle: relay
      - mqtt.publish:
          topic: "hsg/switch-socket/toggle"
          payload: "switch toggled"
    on_release:
      - switch.toggle: relay
      - mqtt.publish:
          topic: "hsg/switch-socket/toggle"
          payload: "switch toggled"

switch:
  - platform: gpio
    name: "Sonoff Basic Relay"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes
